### ISSUE TITLE
Add resource/endpoint to return list of versions per activity

### ISSUE THREAD

**Issue by wfowlks** [Kaleido-Biosciences/cabinet#10]
## Description
We need an endpoint to retrieve a list of PlateMapDTOs from Cabinet to based on the requested ActivityName in order for Fetch to generate ActivitySummaries

## Suggested Implementation

- [x] Create a new service DTO object called PlateMapDTO with the following structure
```
  {
    "activityName": "string",
    "checksum": "string",
    "id": integer,
    "lastModified": "date",
    "status": "DRAFT|COMPLETED"
  }
```
- [x] Create the following method in PlateMapRepository.java with a custom query to return only the information in the above JSON
`Optional<PlateMapDTO> findAllSummariesByActivityName(@Param("activityName") String activityName;`
- [x] Create a new **GET** REST Endpoint in PlateMapResource.java for `/plate-map-summary/{activityName}` where the parameter `activityName` is the name of the activity (e.g. G123) to have `List<PlateMapDto>` returned

## Other information
Example of using @Query annotation in the repository class to limit returned attributes is here: https://stackoverflow.com/questions/37167422/how-to-fetch-only-selected-attributes-of-an-entity-using-spring-jpa
We may want to abstract this code to the Cabinet Client referenced in Fetch: https://github.com/Kaleido-Biosciences/fetch/issues/32

**Comment by psk788** [comment]
The endpoint should be /plate-maps/list/{activityName} with param activityName as the name of the activity (e.g. G1234) to be searched against.

It should return a list of plate-maps without the data attribute in the below structure.
`
[
  {
    "activityName": "G1234",
    "checksum": "doweneedthis?",
    "id": 1,
    "lastModified": "2020-03-04T14:39:37.065Z",
    "status": "DRAFT"
  },
  {
    "activityName": "G1234",
    "checksum": "doweneedthis?",
    "id": 2,
    "lastModified": "2020-03-04T14:39:37.065Z",
    "status": "COMPLETED"
  }
]
`
An associated service in PlateMapService.java and repository function in PlateMapRepository.java should be updated to select all relevant fields from the database, without the data column (to increase performance)
Example limiting queries is here: https://stackoverflow.com/questions/37167422/how-to-fetch-only-selected-attributes-of-an-entity-using-spring-jpa

**Comment by QpYujin** [comment]
Code is pushed to feature/versionList

**Comment by QpYujin** [comment]
Will be closed when pull request is merged
