### ISSUE TITLE
Add endpoint to get the payload for an activity

### ISSUE THREAD

**Issue by wfowlks** [Kaleido-Biosciences/cabinet#11]
We need 2 endpoints to retrieve the plate map data / payload for the given statuses

- [x] Draft - should only need an ActivityName

- [x] Completed - Need a timestamp & ActivityName

**Comment by QpYujin** [comment]
Code is pushed to feature/payloadEndpoint, both apis are up, but Completed has not been tested yet due to the timestamp format issue. Also regarding the plate map data/payload, does it mean just the Data string inside platemap, or the entire platemap payload?

**Comment by wfowlks** [comment]
> Completed has not been tested yet due to the timestamp format issue.

Should we instead pass the checksum/hash of the plate to retrieve it by? Because then you wouldn't need the activity # assuming there are no collisions. @psk788 thoughts?

**Comment by psk788** [comment]
I'd agree with Wes. The fewer the parameters we can pass and the simpler the parameters (timestamp is almost always difficult due to all the format possibilities) the better.  If we know checksum/hash is distinct than we should use that.

**Comment by QpYujin** [comment]
Ok, checksum is currently created using timestamp, data, and activity name, so it would be unique everytime, will change to that

**Comment by QpYujin** [comment]
Current api retrieves only using checksum
