### ISSUE TITLE
Add endpoints for finding Platemaps

### ISSUE THREAD

**Issue by wfowlks** [Kaleido-Biosciences/cabinet#6]
We will need to find plate maps based on the `activityName`

I see the following search/retrievals: 

- [x] Activity Name & Status (Draft/Completed)

- [x] Activity Name & lastModified

- [x] Activity Name & checksum

- [x]  Activity Name (This will be used for returning a list of status, and lastModified)

**Comment by QpYujin** [comment]
Code is pushed to feature/retrieve_by_activityName branch, api link is /api/plate-maps/details (POST call)
`API Request Body
{
   "id": ,
    "status": ,
    "lastModified": ,
    "checksum": ,
    "activityName": ,
    "data":  
}`
This api combines all 4 of the search/retrieval requirement into one, just omit the non-required key/value pair(do not leave an empty value), depending on the search requirement, will push fetch code which calls this latest api

**Comment by QpYujin** [comment]
Merged
