### ISSUE TITLE
Modify the save endpoint

### ISSUE THREAD

**Issue by wfowlks** [Kaleido-Biosciences/cabinet#7]
The save endpoint should do the following: 

When a new plate is passed to be saved (Draft & Completed) it should also take a checksum value which is the checksum from the most recent "fresh" plate map. 

The save endpoint should check to see if the checksum matches the most recent draft for the given activity, if it does, write the new plate map and calculate the new checksum for the plate, the response should include the new checksum for the caller.

However if the checksum is not the most recent a response code of `409` (Conflict) should be returned and the response should state that the checksum is not the most recent, please get the most recent. 

- [x] Update the parameters of the POST and PUT to include a checksum

- [x] Change the response Entity to String

- [x] Return the new checksum or a `409` response code

**Comment by QpYujin** [comment]
Code is pushed to feature/checksum, POST and PUT api will now generate checksum and lastModified values to be inserted to database, PUT will first check whether the data in the database has the same checksum as the incoming new data before updating database. Response Entity is now of type string, and will return checksum value when call is successful, or send error message/code. Will wait for someone to test it before creating a pull request

**Comment by psk788** [comment]
I can see the liquibase changelog [20200212203810_changelog.xml](../blob/feature/checksum/src/main/resources/config/liquibase/changelog/20200212203810_changelog.xml) but I don't see it being called anywhere in the [master.xml](../blob/feature/checksum/src/main/resources/config/liquibase/master.xml) so I dont believe this will work.

**Comment by psk788** [comment]
The liquibase issues were resolved when I removed all references to activity and rebuilt the database.

**Comment by QpYujin** [comment]
This ticket is completed
